apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    verbs: ["create", "delete", "update"]
    resources:
      - group: ""
        resources: ["pods"]
  - level: None  # ignore everything else
